//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtlantCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_ORG
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public int PARENT_ID { get; set; }
        public string ADRES { get; set; }
        public string PHONE { get; set; }
        public string KOD_PODTV { get; set; }
        public Nullable<int> M_ORG_TYPE_ID { get; set; }
        public Nullable<int> TZ { get; set; }
        public Nullable<int> M_ORG_ID_TEH_OTDEL { get; set; }
        public int DEISTV { get; set; }
    }
}
