//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtlantCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_SEANS_TIME
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string MIN_TIME { get; set; }
        public string MAX_TIME { get; set; }
        public Nullable<int> M_ORG_ID { get; set; }
        public Nullable<int> MIN_TIME_MINUTES { get; set; }
        public Nullable<int> MAX_TIME_MINUTES { get; set; }
    }
}
