//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtlantCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_SMS_TEMPLATE
    {
        public int ID { get; set; }
        public Nullable<int> M_SMS_TEMPLATE_TYPE_ID { get; set; }
        public string SOOB { get; set; }
        public Nullable<int> M_ORG_ID { get; set; }
    }
}
