//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtlantCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_ANK
    {
        public int ID { get; set; }
        public string SURNAME { get; set; }
        public string NAME { get; set; }
        public string SECNAME { get; set; }
        public Nullable<short> SEX { get; set; }
        public Nullable<System.DateTime> BIRTHDAY { get; set; }
        public string PHONE_MOBILE { get; set; }
        public string PHONE_HOME { get; set; }
        public string REGION { get; set; }
        public string CITY { get; set; }
        public string STREET { get; set; }
        public string HOUSE { get; set; }
        public string FLAT { get; set; }
        public string CORPUS { get; set; }
        public string DISTRICT { get; set; }
        public string POST_INDEX { get; set; }
        public Nullable<short> IST_INFO { get; set; }
        public Nullable<int> FIO_INFO_ID { get; set; }
        public Nullable<int> USER_REG { get; set; }
        public Nullable<System.DateTime> DATE_REG { get; set; }
        public byte[] PHOTO { get; set; }
        public Nullable<int> M_ORG_ID { get; set; }
        public int BONUS { get; set; }
        public int AKTIVIST { get; set; }
        public Nullable<decimal> GPS_LG { get; set; }
        public Nullable<decimal> GPS_LT { get; set; }
        public int VIP { get; set; }
        public Nullable<System.DateTime> D_SKRYT_PO { get; set; }
        public int ID_CODE { get; set; }
    }
}
