//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtlantCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_DEISTV
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> D_START { get; set; }
        public Nullable<System.DateTime> D_FIN { get; set; }
        public Nullable<int> M_ORG_ID { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<int> M_DEISTV_ID { get; set; }
        public string MESS { get; set; }
        public Nullable<int> O_ANK_ID { get; set; }
        public Nullable<int> O_SKLAD_PR_ID { get; set; }
        public Nullable<int> O_SKLAD_RAS_ID { get; set; }
        public Nullable<int> O_RAS_DOK_ID { get; set; }
    }
}
