//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtlantCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_KALEN_PROD
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> D_START { get; set; }
        public Nullable<System.DateTime> D_MODIF { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<int> M_ORG_ID { get; set; }
        public Nullable<int> GOD { get; set; }
        public Nullable<int> MES { get; set; }
        public string NAME_AK { get; set; }
        public Nullable<int> M_PRODUCT_ID_TOVAR { get; set; }
        public Nullable<int> M_PRODUCT_ID_PODAROK { get; set; }
        public Nullable<decimal> COST { get; set; }
        public Nullable<System.DateTime> D_NAPOLN_S { get; set; }
        public Nullable<System.DateTime> D_NAPOLN_PO { get; set; }
        public Nullable<System.DateTime> D_VLYUB_S { get; set; }
        public Nullable<System.DateTime> D_VLYUB_PO { get; set; }
        public Nullable<System.DateTime> D_PROD_S { get; set; }
        public Nullable<System.DateTime> D_PROD_PO { get; set; }
        public Nullable<System.DateTime> D_PERIOD_S { get; set; }
        public Nullable<System.DateTime> D_PERIOD_PO { get; set; }
    }
}
