//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtlantCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_NASTR
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> D_START { get; set; }
        public Nullable<System.DateTime> D_MODIF { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<int> M_ORG_ID { get; set; }
        public string SMS_LOGIN { get; set; }
        public string SMS_PASSWORD { get; set; }
        public string SMS_SENDER { get; set; }
        public string PHONE_MOBILE { get; set; }
        public string SIP_KEY { get; set; }
        public string SIP_SECRET { get; set; }
        public int DILER_C_ACCESS { get; set; }
        public string VNESH_VID_REG { get; set; }
        public int SHOW_KONT { get; set; }
        public int SMS_AUTO_SEND { get; set; }
    }
}
