//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtlantCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_PRODL
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> D_START { get; set; }
        public Nullable<int> M_ORG_ID { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<int> M_SOPR_STATUS_ID { get; set; }
        public Nullable<int> M_SOPR_DOP_ID { get; set; }
        public Nullable<int> O_ANK_ID { get; set; }
        public int IS_SROCHNO { get; set; }
    }
}
