//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtlantCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_PRAVO_REJ
    {
        public int ID { get; set; }
        public Nullable<int> S_USER_ID { get; set; }
        public Nullable<int> M_PRAVO_REJ_ID { get; set; }
        public Nullable<int> READ1 { get; set; }
        public Nullable<int> WRITE1 { get; set; }
    }
}
