//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtlantCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_RAS_DOK
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> D_START { get; set; }
        public Nullable<System.DateTime> D_MODIF { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<int> M_ORG_ID { get; set; }
        public Nullable<int> M_RASHOD_STAT_ID { get; set; }
        public Nullable<System.DateTime> D_SCHET { get; set; }
        public string N_SCHET { get; set; }
        public string POSTAV_NAME { get; set; }
        public string REK { get; set; }
        public Nullable<decimal> COST { get; set; }
        public Nullable<int> KOLVO { get; set; }
        public Nullable<decimal> SUMMA_RASH { get; set; }
        public Nullable<int> S_USER_ID { get; set; }
        public string MOTIV { get; set; }
        public Nullable<decimal> SUMMA_VID { get; set; }
        public Nullable<decimal> VOZVR { get; set; }
        public Nullable<decimal> RASHOD { get; set; }
    }
}
