//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtlantCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_REK_ANK
    {
        public int ID { get; set; }
        public string SURNAME { get; set; }
        public string NAME { get; set; }
        public string SECNAME { get; set; }
        public string PHONE { get; set; }
        public Nullable<int> M_ORG_ID { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<System.DateTime> D_START { get; set; }
        public Nullable<int> O_ANK_ID { get; set; }
        public int SKR { get; set; }
        public Nullable<int> O_ANK_ID_REK { get; set; }
    }
}
