//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtlantCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_SEANS
    {
        public int ID { get; set; }
        public Nullable<int> O_ANK_ID { get; set; }
        public Nullable<int> M_SEANS_TIME_ID { get; set; }
        public Nullable<int> M_SEANS_PLACE_ID { get; set; }
        public Nullable<System.DateTime> SEANS_DATE { get; set; }
        public int SEANS_STATE { get; set; }
        public Nullable<int> M_RYAD_ID { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<System.DateTime> D_START { get; set; }
        public Nullable<int> LANE { get; set; }
        public Nullable<int> USERID_REG { get; set; }
        public Nullable<System.DateTime> D_REG { get; set; }
        public int BEZ_REG { get; set; }
        public Nullable<int> M_ORG_ID { get; set; }
        public int ANK { get; set; }
        public Nullable<System.DateTime> D_MODIF { get; set; }
        public int IS_FIRST_KONT_SEANS { get; set; }
        public int FROM_ZVONOK { get; set; }
        public int IS_GOST { get; set; }
    }
}
