//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtlantCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_SEANS_COMMENT
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> SEANS_DATE { get; set; }
        public string COMMENT { get; set; }
        public Nullable<int> USERID { get; set; }
    }
}
