//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtlantCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_SERVICE
    {
        public int ID { get; set; }
        public Nullable<int> O_ANK_ID { get; set; }
        public Nullable<int> M_SERVICE_TYPE_ID { get; set; }
        public Nullable<int> M_PRODUCT_ID { get; set; }
        public string SERIAL_NUMBER { get; set; }
        public byte[] PRODUCT_PHOTO { get; set; }
        public byte[] GUARANTEE_PHOTO { get; set; }
        public byte[] PRODUCT_CHECK { get; set; }
        public string COMMENT { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<System.DateTime> D_START { get; set; }
        public Nullable<int> M_ORG_ID { get; set; }
        public Nullable<System.DateTime> D_MODIF { get; set; }
        public Nullable<int> M_SERVICE_TYPE_ID_TEH_OTDEL { get; set; }
        public Nullable<System.DateTime> DATE_TEH_OTDEL { get; set; }
        public Nullable<int> S_USER_ID_TEH_OTDEL { get; set; }
        public string COMMENT_TEH_OTDEL { get; set; }
        public Nullable<int> M_ORG_ID_TEH_OTDEL { get; set; }
    }
}
