//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtlantCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_SKLAD_RAS_PRODUCT
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> D_START { get; set; }
        public Nullable<System.DateTime> D_MODIF { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<int> M_ORG_ID { get; set; }
        public Nullable<int> O_SKLAD_RAS_ID { get; set; }
        public Nullable<int> M_PRODUCT_ID { get; set; }
        public Nullable<int> KOLVO { get; set; }
        public Nullable<decimal> TSENA { get; set; }
        public Nullable<decimal> SKIDKA { get; set; }
        public Nullable<decimal> COST { get; set; }
        public int IS_AKTSIYA { get; set; }
        public int IS_VID { get; set; }
        public Nullable<System.DateTime> D_VID { get; set; }
        public Nullable<decimal> OPL_VSEGO { get; set; }
        public Nullable<decimal> OPL_OST { get; set; }
        public Nullable<System.DateTime> D_DEISTV { get; set; }
        public Nullable<System.DateTime> D_SKRYT_PO { get; set; }
        public Nullable<int> KOLVO_POS { get; set; }
    }
}
