//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtlantCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_SKLAD_RAS_PRODUCT_OPL
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> D_START { get; set; }
        public Nullable<System.DateTime> D_MODIF { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<int> M_ORG_ID { get; set; }
        public Nullable<int> O_SKLAD_RAS_PRODUCT_ID { get; set; }
        public Nullable<decimal> OPL { get; set; }
        public Nullable<System.DateTime> D_OPL { get; set; }
        public Nullable<int> M_METOD_OPL_ID { get; set; }
        public string SERIAL { get; set; }
    }
}
