//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtlantCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_SKLAD_RAS
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> D_START { get; set; }
        public Nullable<System.DateTime> D_MODIF { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<int> M_ORG_ID { get; set; }
        public Nullable<System.DateTime> D_SCHET { get; set; }
        public string N_SCHET { get; set; }
        public string SURNAME { get; set; }
        public string NAME { get; set; }
        public string SECNAME { get; set; }
        public string STREET { get; set; }
        public string POST_INDEX { get; set; }
        public string PHONE_MOBILE { get; set; }
        public Nullable<int> O_ANK_ID { get; set; }
        public Nullable<int> S_USER_ID { get; set; }
        public Nullable<int> SEMYA_VSEGO { get; set; }
        public Nullable<int> HODIT { get; set; }
    }
}
