//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtlantCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_SMS_SEND
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> D_START { get; set; }
        public Nullable<System.DateTime> D_MODIF { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<int> M_ORG_ID { get; set; }
        public Nullable<int> O_ANK_ID { get; set; }
        public string SOOB { get; set; }
        public Nullable<System.DateTime> SEND_DATE { get; set; }
        public string SEND_LOGIN { get; set; }
        public Nullable<int> SEND_STATE { get; set; }
        public Nullable<int> SEND_NUM { get; set; }
        public Nullable<int> M_SMS_TEMPLATE_ID { get; set; }
    }
}
