//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtlantCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_UVEDOML
    {
        public int ID { get; set; }
        public string FIO { get; set; }
        public string PHONE { get; set; }
        public Nullable<int> O_ANK_ID { get; set; }
        public Nullable<int> M_VID_SOB_ID { get; set; }
        public Nullable<System.DateTime> D_SOB { get; set; }
        public string COMMENT { get; set; }
        public Nullable<int> ISP { get; set; }
        public Nullable<System.DateTime> D_START { get; set; }
        public Nullable<System.DateTime> D_MODIF { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<int> M_ORG_ID { get; set; }
        public Nullable<int> O_SEANS_ID { get; set; }
        public Nullable<int> O_KONT_ANK_ID { get; set; }
        public Nullable<int> O_SKLAD_RAS_ID { get; set; }
        public int GR { get; set; }
        public Nullable<int> O_SKLAD_RAS_NOMER { get; set; }
    }
}
