//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtlantCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_VIPIS
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> D_START { get; set; }
        public Nullable<System.DateTime> D_MODIF { get; set; }
        public Nullable<int> M_ORG_ID { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<int> O_ANK_ID { get; set; }
        public Nullable<int> M_ZABOL_GROUP_ID { get; set; }
        public string ZABOL_TEXT { get; set; }
        public string ULUCH_TEXT { get; set; }
        public Nullable<System.DateTime> D_ULUCH { get; set; }
        public string LINK { get; set; }
        public string LINK_POSLE { get; set; }
    }
}
