//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtlantCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_ZARPL_FIO
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> D_START { get; set; }
        public Nullable<System.DateTime> D_MODIF { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<int> M_ORG_ID { get; set; }
        public Nullable<int> S_USER_ID { get; set; }
        public Nullable<int> O_ZARPL_ID { get; set; }
        public Nullable<int> DNI { get; set; }
        public Nullable<int> CHAS { get; set; }
        public Nullable<decimal> S_CH { get; set; }
        public Nullable<decimal> SUMMA { get; set; }
        public Nullable<decimal> VALOV_DOHOD { get; set; }
        public Nullable<decimal> PROTS { get; set; }
        public Nullable<decimal> BONUS { get; set; }
        public Nullable<decimal> SHTRAF { get; set; }
        public Nullable<decimal> ZARPL { get; set; }
    }
}
