//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtlantCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_ZADACHA
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> D_START { get; set; }
        public Nullable<System.DateTime> D_MODIF { get; set; }
        public Nullable<int> M_ORG_ID { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<int> M_ORG_ID_ZADACHA { get; set; }
        public Nullable<System.DateTime> D_BEG { get; set; }
        public Nullable<System.DateTime> D_END { get; set; }
        public string TEMA { get; set; }
        public string ZADACHA { get; set; }
        public Nullable<System.DateTime> D_VIP { get; set; }
        public Nullable<int> USERID_VIP { get; set; }
    }
}
