//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtlantCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_ZVONOK
    {
        public int ID { get; set; }
        public int O_ANK_ID { get; set; }
        public Nullable<System.DateTime> D_END_ISKL { get; set; }
        public Nullable<int> M_ISKL_ID { get; set; }
        public string OPERATOR { get; set; }
        public Nullable<System.DateTime> D_MODIF { get; set; }
        public Nullable<System.DateTime> D_START { get; set; }
        public string COMMENT { get; set; }
        public Nullable<int> M_ORG_ID { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<int> D_START_USER_ID { get; set; }
        public Nullable<int> D_MODIF_USER_ID { get; set; }
        public Nullable<int> D_END_ISKL_USER_ID { get; set; }
    }
}
