//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtlantCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_USER
    {
        public int ID { get; set; }
        public int S_USER_ROLE_ID { get; set; }
        public string SURNAME { get; set; }
        public string NAME { get; set; }
        public string SECNAME { get; set; }
        public Nullable<int> M_ORG_ID { get; set; }
        public string AspNetUsersId { get; set; }
        public byte[] PHOTO { get; set; }
        public Nullable<System.DateTime> D_START { get; set; }
        public Nullable<System.DateTime> BIRTHDAY { get; set; }
        public Nullable<System.DateTime> HIRE_DATE { get; set; }
        public int IS_ADM { get; set; }
        public string SIP_LOGIN { get; set; }
        public string SIP_PASSWORD { get; set; }
        public string PHONE_MOBILE { get; set; }
        public int IS_DILER_A { get; set; }
        public int IS_DILER_C { get; set; }
        public Nullable<int> M_ORG_ID_DILER_A { get; set; }
        public Nullable<int> M_ORG_ID_DILER_C { get; set; }
        public Nullable<System.DateTime> DISMISS_DATE { get; set; }
    }
}
